.github/pull_request_template.md, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
This adds the `publishedAt` timestamp to the `Subscription` RPC payload. See [the specs](https://github.com/WalletConnect/walletconnect-docs/pull/473).
Unit tests.
=> feat: message timestamp in subscription payload

relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
This disables the message length validation as per https://github.com/WalletConnect/walletconnect-docs/pull/489.
Unit tests.
=> fix: disable message limit

.github/workflows/ci.yaml, .github/workflows/release.yaml, README.md
This updates the readme and the release pipeline changes (which should now require tests to pass).
Untested.
=> docs: basic readme

relay_rpc/src/rpc.rs
This adds custom error codes. Currently the only one is the authorization error.
Untested.
=> feat: custom error codes

relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
Add `tag` field to `SubscriptionData` field, so that subscribers can be aware of the type of incoming message. 
E.g. Cast server will be able to distinguish `pushDelete` without having to decrypt the message.
=> feat: add tag field to subscription data struct

relay_client/src/client.rs, relay_client/src/client/fetch.rs, relay_rpc/src/auth.rs, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
This adds the payload and client methods for the new `irn_fetchMessages` and `irn_batchFetchMessages` RPC. See https://github.com/WalletConnect/walletconnect-docs/pull/459 for specs.
Note: The `fetch_stream()` API is actually covered with tests in the relay.
Manually + relay integration tests.
=> feat: fetch api

relay_client/src/client/stream.rs, relay_rpc/src/domain.rs, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
We are gradually migrating to `19` digits rpc_id's. 
This PR requires the `MessageId` to be at least 10 digits long
Unit
=> feat: Validate MessageId's (rpc_id)

relay_client/src/http.rs, relay_client/src/websocket.rs
This exposes the `irn_batchReceive` RPC method to the clients.
With the relay tests.
=> feat: batch receive methods for the client

relay_client/src/websocket.rs, relay_client/src/websocket/inbound.rs
Some clients will need access to `tag` and 'id` fields from incoming messages.
Passing them throught now.
Resolves #25 
Ran tests.
=> feat: add tag field to PublishedMessage

relay_rpc/src/rpc.rs
This adds a 'too many requests' error for use with the HTTP RPC client.
Untested.
=> feat: too many requests error

Cargo.toml, README.md, examples/webhook.rs, relay_rpc/src/jwt.rs, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/watch.rs
This adds a webhook example and some minor fixes to RPC types surrounding watch registration and webhook dispatch.
Note: To run the example make sure the relay is running locally to be able to dispatch webhooks to the local server.
```
[publisher] client id: did:key:z6MkrNnCuEkjEE2wbF4NUQwX6RoBWYRn2HC3rFdAMM2CKZvV
[subscriber] client id: did:key:z6Mkge373J7U6BfvLsCBzDA1Hf7W3wEtUJSApbfmGDGw1gXM
[subscriber] watch registered: relay_id=did:key:z6MksL1xGunmRDzskniANbwMzPMUWUdyuUVfrd4WhvgHKK1Q
[publisher] watch registered: relay_id=did:key:z6MksL1xGunmRDzskniANbwMzPMUWUdyuUVfrd4WhvgHKK1Q
[publisher] message published: topic=37931305f08feb99a361828a30529aa00921d657d7d2df636b0a9cec3d79d71c message=Hello WalletConnect!
[subscriber] received message: Hello WalletConnect!
[webhook] publisher: …
```
=> feat: webhook example

justfile, relay_client/src/http.rs, relay_rpc/src/rpc/msg_id.rs, relay_rpc/src/rpc/watch.rs
- Add `watch_register_behalf()` function which allows passing-through `register_auth` payload from client
- Non-successful RPC requests will include the error body
- `just fmt` will auto-format instead of just `--check`
- `get_message_id()` refactor left-over from https://github.com/WalletConnect/WalletConnectRust/pull/39
Resolves #40
With archive refactor
=> feat: watch register behalf

relay_rpc/src/auth/cacao/payload.rs, relay_rpc/src/auth/cacao/tests.rs
Required by https://github.com/WalletConnect/walletconnect-specs/pull/139
The identity key will no longer be in Cacao resources but in the audience. In order to avoid breaking changes we accept both versions. If Identity Key is present in both resources and audience the latter is taken. 
Resolves #45  
Unit tests supported by data generated by Kotlin SDK
=> feat: Update cacao identity resolution

relay_client/Cargo.toml
Fixing some Dependabot and `cargo audit` errors in Notify Server, need to bump the version in this repo or is incompatible with the version I want to use in Notify Server.
Good news is WalletConnectRust has zero security warnings after this PR.
https://github.com/WalletConnect/notify-server/pull/232
=> fix: RUSTSEC-2023-0065

.github/workflows/ci.yaml, .github/workflows/event_pr.yaml
Only checks the PR title, rather than the commits inside, because this is squashed
Not tested
=> fix: only check PR title

Cargo.toml, relay_rpc/src/auth/cacao/header.rs, relay_rpc/src/auth/cacao/signature.rs
- Refactors magic strings so they can be used in Notify Server test cases.
- Fixes that CI doesn't build the cacao feature.
Not tested
=> chore: refactor magic strings

relay_client/src/websocket.rs
Allows cloning the `PublishedMessage` so that it can be used inside of a `broadcast::Receiver<T>`
Required for [this PR](https://github.com/WalletConnect/notify-server/pull/264)
Not tested
=> fix: allow cloning PublishedMessage

relay_client/src/http.rs, relay_client/src/websocket.rs, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
This adds support for 'blocking' subscriptions, i.e. disabling the optimistic response by the relay.
Existing tests.
=> feat: support blocking subscriptions

relay_rpc/src/rpc/watch.rs
This adds original message ID to the `WatchEventPayload` as requested for the Notify server.
See also the relay update: https://github.com/WalletConnect/rs-relay/pull/1418
Existing tests.
=> feat: add message id to watch event payload

relay_rpc/src/auth/cacao/payload.rs
When converging Keys Server to this module we overlooked difference in this function
Resolves # (issue)
Was tested previously. Caused regression
We need to make sure if Notify Server doesn't depend on it
=> fix: do not lowercase caip_10 adresses

examples/webhook.rs, relay_rpc/Cargo.toml, relay_rpc/src/rpc/watch.rs
Updates the format to match [the specs](https://github.com/WalletConnect/walletconnect-specs/pull/127/files#r1468254981).
Also makes alloy dependencies optional (dependent on cacao feature) to avoid dependency conflicts with relay.
Not tested
=> fix: update events to array to match specs

.github/workflows/ci.yaml, examples/http_client.rs, examples/webhook.rs, justfile
`--examples` weren't being checked, and I'm not sure why we were using `--tests` instead of simply `--all-targets` which covers everything.
N/A
=> fix(clippy): examples

Cargo.toml, examples/websocket_client.rs, relay_client/src/error.rs, relay_client/src/http.rs, relay_client/src/lib.rs, relay_client/src/websocket.rs, relay_client/src/websocket/connection.rs, relay_client/src/websocket/fetch.rs, relay_client/src/websocket/inbound.rs, relay_client/src/websocket/outbound.rs, relay_client/src/websocket/stream.rs, relay_rpc/Cargo.toml, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/error.rs, relay_rpc/src/rpc/tests.rs
This reworks the RPC errors to be serializable and deserializable from the `data` field of JSONRPC error response. Both the HTTP and websocket clients in this crate make use of the new errors by deserializing relay RPC responses into strongly-typed errors.
Clients in other SDKs should implement their own reconstruction based on the following JSONRPC error response fields:
- `code`: the general class of errors to distinguish between retryable and permanent errors;
- `data`: the string tag specifying error kind within that class;
- `message`: string message detailing the error.
The error codes are (mostly) consistent with the old error codes & the JSONRPC specs. What's changed:
- Parameter validation error code changed from `-32602` (invalid params) to a more generic `-32600` (invalid …
=> feat: error handling overhaul

relay_rpc/src/auth/cacao.rs, relay_rpc/src/auth/cacao/header.rs
"Invalid header" isn't a good error message, this improves the error message. The header is already parsed as a valid structure, all this does is check the type (`t`) field.
Not tested. Passes compilation, and nothing depends on this error. It's just used to help debugging a 400.
=> chore: improve header error

justfile, relay_rpc/src/auth/cacao/payload.rs, relay_rpc/src/jwt.rs
Prereq for https://github.com/WalletConnect/notify-server/pull/398
New tests
=> feat: identity key from URL

relay_client/src/http.rs, relay_client/src/lib.rs, relay_client/src/websocket.rs, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
This creates a separate `irn_subscribeBlocking` and `irn_batchSubscribeBlocking` methods which were previously behind the `block` flag in the main method payloads.
Also removes the requirement to pass subscription IDs to unsubscribe.
Relay integration.
=> feat: seaprate blocking methods

blockchain_api/Cargo.toml, relay_client/Cargo.toml, relay_rpc/Cargo.toml
Bumps to the latest reqwest version and related dependencies. Necessary for the rennovatebot PR on Notify Server: https://github.com/WalletConnect/notify-server/pull/467
Existing tests and in https://github.com/WalletConnect/notify-server/pull/467
=> fix: bump http deps

blockchain_api/Cargo.toml, relay_client/Cargo.toml, relay_rpc/Cargo.toml
This PR adds a license to workspaces. The license type is the same as in the root package: [Apache-2.0](https://github.com/WalletConnect/WalletConnectRust/blob/2ce3a45f4d9ada7f05441a690a766ddf79f086f0/Cargo.toml#L7).
This should fix [license check errors](https://github.com/WalletConnect/blockchain-api/actions/runs/8849202224/job/24301511183?pr=644#step:4:17).
Not tested.
=> fix: adding license to workspaces

examples/http_client.rs, examples/webhook.rs, examples/websocket_client.rs, relay_client/src/http.rs, relay_client/src/websocket.rs, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs, relay_rpc/src/rpc/watch.rs
This adds the necessary new fields for the [verify attestation API](https://github.com/WalletConnect/walletconnect-specs/pull/240).
Relay integration.
=> feat: publish verify attestation

relay_rpc/Cargo.toml, relay_rpc/src/auth/cacao.rs, relay_rpc/src/auth/cacao/signature/eip1271.rs, relay_rpc/src/auth/cacao/signature/eip191.rs, relay_rpc/src/auth/cacao/signature/eip6492.rs, relay_rpc/src/auth/cacao/signature/mod.rs, relay_rpc/src/auth/cacao/signature/test_helpers.rs
Bumps alloy to the latest version; this is what Yttrium uses and Blockchain API uses both these libraries.
Not tested
=> fix: bump alloy to latest

.github/workflows/ci.yaml, relay_client/src/http.rs, relay_client/src/lib.rs, relay_client/src/websocket.rs, relay_rpc/Cargo.toml, relay_rpc/src/auth/cacao.rs, relay_rpc/src/auth/cacao/payload.rs, relay_rpc/src/auth/cacao/signature/eip1271.rs, relay_rpc/src/auth/cacao/signature/eip191.rs, relay_rpc/src/auth/cacao/signature/eip6492.rs, relay_rpc/src/auth/cacao/signature/mod.rs, relay_rpc/src/jwt.rs, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
Implements the TVF data fields as per [spec](https://www.notion.so/walletconnect/TVF-tracking-in-WalletKit-tech-doc-14a3a661771e8094a056db28c0005e6e#16f3a661771e80acb49dd0e96347d80e).
Other changes:
- Cacao tests are now hidden behind a feature flag, effectively disabling them until they're fixed or removed.
Additional unit tests.
=> feat: tvf data in publish payload

relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
This switches correlation ID format to `i64`.
Untested.
=> fix: use i64 for correlation ID

relay_client/src/http.rs, relay_client/src/websocket.rs, relay_rpc/src/rpc.rs, relay_rpc/src/rpc/tests.rs
This adds the analytics data to the `wc_proposeSession` and `wc_approveSession` methods.
Existing tests here and in the relay.
=> fix: session methods analytics
